[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicy = "on-failure"

[env]
NODE_ENV = "production"
PORT = "5000" 